# Generated by Django 5.1 on 2026-04-22 18:10

import django.db.models.deletion
from django.db import migrations, models

ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'


def backfill_referral_codes(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all().iterator():
        if user.referral_code:
            continue
        seed = ''.join(ch for ch in (user.full_name or '').upper() if ch.isalnum())[:4] or 'BMG'
        suffix = format(abs(hash(str(user.pk))) % (32 ** 4), 'x').upper()
        suffix = ''.join(ALPHABET[int(char, 16) % len(ALPHABET)] for char in suffix[-4:].rjust(4, '0'))
        candidate = f'{seed}{suffix}'
        counter = 0
        while User.objects.filter(referral_code=candidate).exclude(pk=user.pk).exists():
            counter += 1
            base = str(user.pk).replace('-', '').upper()[:4]
            candidate = f"BMG{base}{counter}"[:16]
        user.referral_code = candidate[:16]
        user.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payoutprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.user'),
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
