# Generated by Django 5.1 on 2026-04-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='owner_share',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be paid to the owner', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (e.g. 29 INR)', max_digits=10),
        ),
    ]
