# Generated by Django 5.1 on 2026-04-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_payment_owner_share_payment_platform_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='bookings.booking')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to='bookings.timeslot')),
            ],
            options={
                'db_table': 'booking_slots',
                'ordering': ['time_slot__date', 'time_slot__start_time'],
                'unique_together': {('booking', 'time_slot')},
            },
        ),
    ]
