# Generated by Django 5.1 on 2026-04-22 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_booking_amounts(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    for booking in Booking.objects.all().iterator():
        if not booking.base_amount:
            booking.base_amount = booking.total_amount
        if booking.discount_amount is None:
            booking.discount_amount = 0
        booking.save(update_fields=['base_amount', 'discount_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_referral_support'),
        ('bookings', '0005_bookingslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='flat', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promo_codes',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='applied_promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.promocode'),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code_snapshot',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='booking',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='referral_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_booking_amounts, migrations.RunPython.noop),
    ]
