# Generated by Django 5.1 on 2026-04-08 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for frontend', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ground_type', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('hockey', 'Hockey'), ('multi_sport', 'Multi Sport'), ('other', 'Other')], max_length=20)),
                ('surface_type', models.CharField(choices=[('natural_grass', 'Natural Grass'), ('artificial_turf', 'Artificial Turf'), ('clay', 'Clay'), ('concrete', 'Concrete'), ('synthetic', 'Synthetic'), ('wooden', 'Wooden'), ('other', 'Other')], default='natural_grass', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('max_players', models.PositiveIntegerField(default=22, help_text='Max players allowed at once')),
                ('rules', models.TextField(blank=True, help_text='Ground rules & policies')),
                ('cancellation_policy', models.TextField(blank=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='grounds', to='grounds.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_grounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grounds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroundImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='grounds/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='grounds.ground')),
            ],
            options={
                'db_table': 'ground_images',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='grounds.ground')),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'ground')},
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_type', models.CharField(choices=[('per_hour', 'Per Hour'), ('two_hours', '2 Hours'), ('three_hours', '3 Hours'), ('half_day', 'Half Day (5 Hours)'), ('full_day', 'Full Day (10 Hours)'), ('custom', 'Custom Duration')], max_length=20)),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10)),
                ('weekend_price', models.DecimalField(blank=True, decimal_places=2, help_text='Weekend/holiday price (leave blank to use regular price)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='grounds.ground')),
            ],
            options={
                'db_table': 'pricing_plans',
                'ordering': ['duration_hours'],
                'unique_together': {('ground', 'duration_type')},
            },
        ),
    ]
